name: Question
description: Submit a question if you are not sure if this is a bug.
title: "[Question] "
labels: question
body:
  - type: markdown
    attributes:
      value: |
        You can ask about future features, game machenic and so on.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true
  - type: textarea
    id: wanted
    attributes:
      label: Additional message
      description: Which aspect would you like to know？
  - type: input
    id: mod-version
    attributes:
      label: Mod version
      placeholder: 0.1.3
    validations:
      required: true
